; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
check_tool = clangtidy
check_src_filters =
    +<src/*>
    +<include/*>
check_flags =
    clangtidy: --config-file=.clang-tidy

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
build_flags =
    ; Enable Stack Protector
    -fstack-protector
    ; BTC and BLE
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
    ; Enable FreeRTOS Support
    ;-DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
build_src_filter = +<*> -<BLE_NimBLE.cpp>

[env:esp32]
monitor_speed = 115200
upload_speed = 115200
board = esp32doit-devkit-v1
monitor_raw = yes
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
framework =
	espidf
	arduino
lib_deps =
    h2zero/esp-nimble-cpp
check_skip_packages = yes
build_flags = 
    -D CONFIG_NIMBLE_CPP_IDF=1
    